# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aa9ec12818deb58c06f2a49443ce04c6909e2ad01f15416d1bfab7dd9a402f5a2c4cd4d42e1d723a05ed3df20c45b857b05945dcb03ab4f15e4736e85d028ee

test:
  secret_key_base: f7abf183e86a35e15fb0a712f9d9dcce77e03ee6a2a53210b479f0eda68b7dec387a2ea96c59c8a6aaa3f2cc5d26a49bf271a365db23b8f0e09bd5f36638ea72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
